"""Fine-tune YOLOv8n on the real pilot's Layer 1 training set
(layer1_boxes.csv, generated by generate_layer1_boxes.py). Same recipe
as the micro-pilot's train_layer1_micro.py -- axis-aligned YOLOv8n from
Ultralytics' pretrained checkpoint, not RBOD's oriented-box variant --
per constitution.md's 2026-09-14 speed-over-manual-annotation decision.
"""

import os
import shutil

import pandas as pd

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CROPS_DIR = os.path.join(PROJECT_ROOT, "data/raw/pnoa_crops")
BOXES_CSV = os.path.join(PROJECT_ROOT, "data/processed/layer1_boxes.csv")
DATASET_DIR = os.path.join(PROJECT_ROOT, "data/processed/yolo_dataset_full")
IMG_SIZE = 600  # matches pull_pnoa_crops.py's PIXELS setting


def build_yolo_dataset():
    df = pd.read_csv(BOXES_CSV)
    img_dir = os.path.join(DATASET_DIR, "images/train")
    lbl_dir = os.path.join(DATASET_DIR, "labels/train")
    os.makedirs(img_dir, exist_ok=True)
    os.makedirs(lbl_dir, exist_ok=True)

    for _, row in df.iterrows():
        src = os.path.join(CROPS_DIR, row["filename"])
        stem = row["filename"].replace(".png", "")
        shutil.copy(src, os.path.join(img_dir, row["filename"]))

        xc = (row["x0"] + row["x1"]) / 2 / IMG_SIZE
        yc = (row["y0"] + row["y1"]) / 2 / IMG_SIZE
        bw = (row["x1"] - row["x0"]) / IMG_SIZE
        bh = (row["y1"] - row["y0"]) / IMG_SIZE
        with open(os.path.join(lbl_dir, f"{stem}.txt"), "w") as f:
            f.write(f"0 {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")

    yaml_content = f"""path: {DATASET_DIR}
train: images/train
val: images/train
names:
  0: barrier
"""
    yaml_path = os.path.join(DATASET_DIR, "dataset.yaml")
    with open(yaml_path, "w") as f:
        f.write(yaml_content)
    print(f"Built YOLO dataset: {len(df)} images -> {DATASET_DIR}")
    return yaml_path


if __name__ == "__main__":
    yaml_path = build_yolo_dataset()

    from ultralytics import YOLO

    model = YOLO("yolov8n.pt")
    model.train(data=yaml_path, epochs=50, imgsz=IMG_SIZE, batch=8, project=DATASET_DIR, name="run", verbose=False)
    print("Training complete.")
